server:
  servlet:
    context-path: /api/v1/

spring:
  servlet:
    multipart: #max image size
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    hikari:
      schema: liblanka
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog.xml
    default-schema: liblanka
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect