server:
  servlet:
    context-path: /api/v1/
  port: 7890

spring:
  servlet:
    multipart: #max image size
      max-file-size: 6MB
      max-request-size: 6MB
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    hikari:
      schema: liblanka
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog.xml
    default-schema: liblanka
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: INFO
